server:
  port: 8848
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meetu?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123abc
    hikari:
      # 连接池中允许的最小连接数
      minimum-idle: 5
      # 连接池中允许的最大连接数
      maximum-pool-size: 10
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired）
      idle-timeout: 30000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired）
      max-lifetime: 1800000
  application:
    name: MeetU
  main:
    banner-mode: off
    lazy-initialization: false
  jmx:
    enabled: false
  # swagger 配置 3.0 防止报错
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1 # 启动时初始化 DispatcherServlet
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 2049202552@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: jvoiovisajmkbijh
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: sakura-meetu
    username: sakura
    password: k01225k
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
  redis:
    port: 6379
    database: 0
    host: localhost
    timeout: 10s
    password: 123abc
    # 连接超时
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大空闲连接
        max-idle: 10
        # 连接池中的最小空间连接
        min-idle: 4
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    locale: zh_CN
# mybatis-plus 区
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    banner: off
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: id
  mapper-locations: classpath:/mapper/*.xml
# Sa-Token
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期  2小时6
  timeout: 7200
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  #  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true
  # 令牌前缀
  token-prefix: Bearer
  # jwt 密钥
  jwt-secret-key: uiournawutojawlkqpoo[]o[31
  # 在每次创建 Token 时的最高循环次数，用于保证 Token 唯一性
  max-try-times: -1
  # 不打印版本
  is-print: off
  is-read-body: off
  is-read-cookie: off
  is-write-header: off
logging:
  level:
    com.sakura.meetu: debug
